import * as XLSX from "xlsx";
import { toast } from "react-toastify";

export interface ExcelColumn {
  header: string; // Display Name (Row 2) - e.g. "Unit"
  key: string;    // Unique Technical Path (Row 1) - e.g. "offenders[0].unit"
  formatter?: (value: any) => string | number; // Optional formatting
}

export const useExcelExport = () => {
  const exportToExcel = (data: any[], fileName: string, columns: ExcelColumn[]) => {
    if (!data || data.length === 0) {
      toast.info("No records to export.");
      return;
    }

    try {
      // Helper to drill down into the JSON safely (e.g. "offenders[0].name")
      const getValue = (obj: any, path: string) => {
        const parts = path.split(/[.[\]]/).filter(Boolean); // Handles dots and brackets
        return parts.reduce((acc, part) => acc && acc[part], obj);
      };

      // 1. Prepare Data
      // Row 1 keys are auto-generated by json_to_sheet from the object keys.
      
      // Create Row 2 (Display Headers)
      const headerRow = columns.reduce((acc, col) => ({ ...acc, [col.key]: col.header }), {});

      // Create Data Rows (Row 3+)
      const dataRows = data.map((item) =>
        columns.reduce((acc, col) => {
          const rawValue = getValue(item, col.key);
          const finalValue = col.formatter ? col.formatter(rawValue) : (rawValue || "");
          return { ...acc, [col.key]: finalValue };
        }, {})
      );

      // Combine: [Display Header Row, ...Data Rows]
      const exportData = [headerRow, ...dataRows];

      // 2. Create Worksheet
      // 'skipHeader: false' means the Object Keys (Technical Paths) become Row 1.
      const worksheet = XLSX.utils.json_to_sheet(exportData, { skipHeader: false });

      // 3. Formatting: Auto-Fit Column Widths (No free space)
      const wscols = columns.map((col) => {
        // Calculate max width based on Header Length AND Data Length
        const maxContentLength = Math.max(
          col.header.length,
          col.key.length,
          ...dataRows.map((row: any) => String(row[col.key] || "").length)
        );
        return { wch: maxContentLength + 3 }; // +3 buffer for spacing
      });
      worksheet["!cols"] = wscols;

      // 4. Download
      const workbook = XLSX.utils.book_new();
      XLSX.utils.book_append_sheet(workbook, worksheet, "Traffic Offences");
      const fullFileName = `${fileName}_${new Date().toISOString().slice(0, 10)}.xlsx`;
      XLSX.writeFile(workbook, fullFileName);

      toast.success("Excel exported successfully!");
    } catch (error) {
      console.error("Excel Export Error:", error);
      toast.error("Failed to generate Excel report.");
    }
  };

  return { exportToExcel };
};