export const ANALYSIS_OFFENCE_TYPES = [
    "Murder/Homicide",
    "Mutiny",
    "Running amok",
    "Escape from custody",
    "Theft",
    "Misappropriation",
    "Insubordination/ Obstruction",
    "Corruption",
    "Accidental Firing",
    "Suicide by Army Pers",
    "Suicide by dependent/ Family member",
    "Attempts suicide by Army Pers",
    "Attempts suicide by dependent/ Family member",
    "Aslt",
    "Affray",
    "Fire Incident",
    "Death of Army Pers",
    "Substance Abuse",
    "Possession",
    "Intoxication",
    "Over Speeding",
];
